# Form implementation generated from reading ui file 'loc_thuoc_dark.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_filter_medicine(object):
    def setupUi(self, dlg_filter_medicine):
        dlg_filter_medicine.setObjectName("dlg_filter_medicine")
        dlg_filter_medicine.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlg_filter_medicine.resize(400, 380)
        dlg_filter_medicine.setMinimumSize(QtCore.QSize(400, 380))
        dlg_filter_medicine.setMaximumSize(QtCore.QSize(400, 380))
        dlg_filter_medicine.setStyleSheet("\n"
"    QDialog { background-color: rgb(39, 57, 71);}\n"
"\n"
"    /* Nhãn tiêu đề mục: Màu xám xanh, không đậm, size vừa phải */\n"
"    QLabel#lbl_st_shelf, QLabel#lbl_st_price, QLabel#lbl_st_status {\n"
"        color: #9AA5B1;\n"
"        font-weight: normal;\n"
"        font-size: 12px;\n"
"    }\n"
"\n"
"    /* Ô chọn ComboBox đồng bộ với Form Thêm thuốc */\n"
"    QComboBox {\n"
"        background-color: #1F2933;\n"
"        border: 1px solid #3E4C59;\n"
"        border-radius: 8px;\n"
"        padding-left: 10px;\n"
"        color:#E4E7EB ;\n"
"        font-size: 13px;\n"
"    }\n"
"\n"
"    QComboBox:focus {\n"
"        border: 1px solid #2563EB;\n"
"    }\n"
"   ")
        self.main_layout = QtWidgets.QVBoxLayout(dlg_filter_medicine)
        self.main_layout.setContentsMargins(35, 30, 35, 30)
        self.main_layout.setSpacing(20)
        self.main_layout.setObjectName("main_layout")
        self.lbl_filter_title = QtWidgets.QLabel(parent=dlg_filter_medicine)
        self.lbl_filter_title.setStyleSheet("font-size: 18px; color: #9AA5B1; font-weight: bold;")
        self.lbl_filter_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_filter_title.setObjectName("lbl_filter_title")
        self.main_layout.addWidget(self.lbl_filter_title)
        self.layout_fields = QtWidgets.QVBoxLayout()
        self.layout_fields.setSpacing(8)
        self.layout_fields.setObjectName("layout_fields")
        self.lbl_st_shelf = QtWidgets.QLabel(parent=dlg_filter_medicine)
        self.lbl_st_shelf.setObjectName("lbl_st_shelf")
        self.layout_fields.addWidget(self.lbl_st_shelf)
        self.cb_filter_shelf = QtWidgets.QComboBox(parent=dlg_filter_medicine)
        self.cb_filter_shelf.setMinimumSize(QtCore.QSize(150, 42))
        self.cb_filter_shelf.setObjectName("cb_filter_shelf")
        self.cb_filter_shelf.addItem("")
        self.layout_fields.addWidget(self.cb_filter_shelf)
        self.lbl_st_price = QtWidgets.QLabel(parent=dlg_filter_medicine)
        self.lbl_st_price.setObjectName("lbl_st_price")
        self.layout_fields.addWidget(self.lbl_st_price)
        self.cb_filter_price = QtWidgets.QComboBox(parent=dlg_filter_medicine)
        self.cb_filter_price.setMinimumSize(QtCore.QSize(150, 42))
        self.cb_filter_price.setObjectName("cb_filter_price")
        self.cb_filter_price.addItem("")
        self.layout_fields.addWidget(self.cb_filter_price)
        self.lbl_st_status = QtWidgets.QLabel(parent=dlg_filter_medicine)
        self.lbl_st_status.setObjectName("lbl_st_status")
        self.layout_fields.addWidget(self.lbl_st_status)
        self.cb_filter_status = QtWidgets.QComboBox(parent=dlg_filter_medicine)
        self.cb_filter_status.setMinimumSize(QtCore.QSize(150, 42))
        self.cb_filter_status.setObjectName("cb_filter_status")
        self.cb_filter_status.addItem("")
        self.layout_fields.addWidget(self.cb_filter_status)
        self.main_layout.addLayout(self.layout_fields)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.main_layout.addItem(spacerItem)
        self.layout_actions = QtWidgets.QHBoxLayout()
        self.layout_actions.setSpacing(15)
        self.layout_actions.setObjectName("layout_actions")
        self.btn_secondary = QtWidgets.QPushButton(parent=dlg_filter_medicine)
        self.btn_secondary.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_secondary.setStyleSheet("color: #E4E7EB; border: 1px solid #E0E6ED; border-radius: 8px; font-weight: bold;")
        self.btn_secondary.setObjectName("btn_secondary")
        self.layout_actions.addWidget(self.btn_secondary)
        self.btn_primary = QtWidgets.QPushButton(parent=dlg_filter_medicine)
        self.btn_primary.setMinimumSize(QtCore.QSize(100, 45))
        self.btn_primary.setStyleSheet("background-color: #2563EB; color: white; border-radius: 8px; font-weight: bold;")
        self.btn_primary.setObjectName("btn_primary")
        self.layout_actions.addWidget(self.btn_primary)
        self.main_layout.addLayout(self.layout_actions)

        self.retranslateUi(dlg_filter_medicine)
        QtCore.QMetaObject.connectSlotsByName(dlg_filter_medicine)

    def retranslateUi(self, dlg_filter_medicine):
        _translate = QtCore.QCoreApplication.translate
        dlg_filter_medicine.setWindowTitle(_translate("dlg_filter_medicine", "Lọc thuốc"))
        self.lbl_filter_title.setText(_translate("dlg_filter_medicine", "Lọc thuốc"))
        self.lbl_st_shelf.setText(_translate("dlg_filter_medicine", "Mã kệ"))
        self.cb_filter_shelf.setItemText(0, _translate("dlg_filter_medicine", "Chọn kệ"))
        self.lbl_st_price.setText(_translate("dlg_filter_medicine", "Giá bán"))
        self.cb_filter_price.setItemText(0, _translate("dlg_filter_medicine", "Chọn khoảng giá"))
        self.lbl_st_status.setText(_translate("dlg_filter_medicine", "Trạng thái"))
        self.cb_filter_status.setItemText(0, _translate("dlg_filter_medicine", "Chọn trạng thái"))
        self.btn_secondary.setText(_translate("dlg_filter_medicine", "Cancel"))
        self.btn_primary.setText(_translate("dlg_filter_medicine", "Save"))
