# Form implementation generated from reading ui file 'search.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_search(object):
    def setupUi(self, dlg_search):
        dlg_search.setObjectName("dlg_search")
        dlg_search.resize(450, 500)
        dlg_search.setStyleSheet("\n"
"    QDialog { background-color: #FFFFFF; }\n"
"    QLineEdit#txt_search {\n"
"        border: none;\n"
"        padding-left: 10px;\n"
"        font-size: 16px;\n"
"        color: #1E293B;\n"
"        background-color: transparent;\n"
"    }\n"
"    QListWidget { border: none; background-color: #FFFFFF; outline: none; }\n"
"    QListWidget::item { border-bottom: 1px solid #F1F5F9; }\n"
"    QListWidget::item:hover { background-color: #F8FAFC; }\n"
"   ")
        self.main_layout = QtWidgets.QVBoxLayout(dlg_search)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.frame_search = QtWidgets.QFrame(parent=dlg_search)
        self.frame_search.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_search.setStyleSheet("border-bottom: 1px solid #E2E8F0; background-color: #F8FAFC;")
        self.frame_search.setObjectName("frame_search")
        self.layout_h_search = QtWidgets.QHBoxLayout(self.frame_search)
        self.layout_h_search.setContentsMargins(20, -1, 20, -1)
        self.layout_h_search.setObjectName("layout_h_search")
        self.lbl_icon = QtWidgets.QLabel(parent=self.frame_search)
        self.lbl_icon.setObjectName("lbl_icon")
        self.layout_h_search.addWidget(self.lbl_icon)
        self.txt_search = QtWidgets.QLineEdit(parent=self.frame_search)
        self.txt_search.setObjectName("txt_search")
        self.layout_h_search.addWidget(self.txt_search)
        self.btn_close = QtWidgets.QPushButton(parent=self.frame_search)
        self.btn_close.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_close.setMaximumSize(QtCore.QSize(60, 30))
        self.btn_close.setStyleSheet("QPushButton { background-color: #F1F5F9; color: #2F3E46; border: 1px solid #E0E6ED; border-radius: 6px; font-size: 12px; } QPushButton:hover { border-color: #2563EB; color: #2563EB; }")
        self.btn_close.setObjectName("btn_close")
        self.layout_h_search.addWidget(self.btn_close)
        self.main_layout.addWidget(self.frame_search)
        self.list_results = QtWidgets.QListWidget(parent=dlg_search)
        self.list_results.setObjectName("list_results")
        self.main_layout.addWidget(self.list_results)

        self.retranslateUi(dlg_search)

    def retranslateUi(self, dlg_search):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_icon.setText(_translate("dlg_search", "🔍"))
        self.txt_search.setPlaceholderText(_translate("dlg_search", "Tìm kiếm thuốc..."))
        self.btn_close.setText(_translate("dlg_search", "Đóng"))
