# Form implementation generated from reading ui file 'them_ke.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_add_shelf(object):
    def setupUi(self, dlg_add_shelf):
        dlg_add_shelf.setObjectName("dlg_add_shelf")
        dlg_add_shelf.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlg_add_shelf.resize(450, 420)
        dlg_add_shelf.setMinimumSize(QtCore.QSize(450, 420))
        dlg_add_shelf.setMaximumSize(QtCore.QSize(450, 420))
        dlg_add_shelf.setStyleSheet("\n"
"    QDialog { background-color: #FFFFFF; }\n"
"    QLabel { color: #64748B; font-weight: normal; font-size: 13px; }\n"
"    QLineEdit {\n"
"        background-color: #F8FAFC;\n"
"        border: 1px solid #E2E8F0;\n"
"        border-radius: 8px;\n"
"        padding-left: 12px;\n"
"        color: #1E293B;\n"
"        font-size: 14px;\n"
"    }\n"
"    QLineEdit:focus { border: 1px solid #2563EB; background-color: #FFFFFF; }\n"
"   ")
        self.lbl_title = QtWidgets.QLabel(parent=dlg_add_shelf)
        self.lbl_title.setGeometry(QtCore.QRect(40, 30, 371, 51))
        self.lbl_title.setStyleSheet("font-size: 20px; color: #475569; font-weight: bold;")
        self.lbl_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.line_header = QtWidgets.QFrame(parent=dlg_add_shelf)
        self.line_header.setGeometry(QtCore.QRect(40, 75, 370, 16))
        self.line_header.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_header.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_header.setObjectName("line_header")
        self.widget = QtWidgets.QWidget(parent=dlg_add_shelf)
        self.widget.setGeometry(QtCore.QRect(40, 335, 371, 61))
        self.widget.setObjectName("widget")
        self.layout_actions = QtWidgets.QHBoxLayout(self.widget)
        self.layout_actions.setContentsMargins(0, 0, 0, 0)
        self.layout_actions.setSpacing(15)
        self.layout_actions.setObjectName("layout_actions")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layout_actions.addItem(spacerItem)
        self.btn_secondary = QtWidgets.QPushButton(parent=self.widget)
        self.btn_secondary.setMinimumSize(QtCore.QSize(110, 48))
        self.btn_secondary.setStyleSheet("background-color: #F1F5F9; color: #475569; border-radius: 10px; font-weight: bold;")
        self.btn_secondary.setObjectName("btn_secondary")
        self.layout_actions.addWidget(self.btn_secondary)
        self.btn_primary = QtWidgets.QPushButton(parent=self.widget)
        self.btn_primary.setMinimumSize(QtCore.QSize(110, 48))
        self.btn_primary.setStyleSheet("background-color: #2563EB; color: white; border-radius: 10px; font-weight: bold;")
        self.btn_primary.setObjectName("btn_primary")
        self.layout_actions.addWidget(self.btn_primary)
        self.widget1 = QtWidgets.QWidget(parent=dlg_add_shelf)
        self.widget1.setGeometry(QtCore.QRect(40, 95, 371, 221))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_id = QtWidgets.QLabel(parent=self.widget1)
        self.lbl_id.setObjectName("lbl_id")
        self.verticalLayout.addWidget(self.lbl_id)
        self.txt_shelf_id = QtWidgets.QLineEdit(parent=self.widget1)
        self.txt_shelf_id.setMinimumSize(QtCore.QSize(100, 30))
        self.txt_shelf_id.setObjectName("txt_shelf_id")
        self.verticalLayout.addWidget(self.txt_shelf_id)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.grid_row_col = QtWidgets.QGridLayout()
        self.grid_row_col.setHorizontalSpacing(20)
        self.grid_row_col.setVerticalSpacing(12)
        self.grid_row_col.setObjectName("grid_row_col")
        self.lbl_row = QtWidgets.QLabel(parent=self.widget1)
        self.lbl_row.setObjectName("lbl_row")
        self.grid_row_col.addWidget(self.lbl_row, 1, 1, 1, 1)
        self.lbl_col = QtWidgets.QLabel(parent=self.widget1)
        self.lbl_col.setObjectName("lbl_col")
        self.grid_row_col.addWidget(self.lbl_col, 1, 0, 1, 1)
        self.txt_shelf_col = QtWidgets.QLineEdit(parent=self.widget1)
        self.txt_shelf_col.setMinimumSize(QtCore.QSize(50, 30))
        self.txt_shelf_col.setObjectName("txt_shelf_col")
        self.grid_row_col.addWidget(self.txt_shelf_col, 5, 0, 1, 1)
        self.txt_shelf_row = QtWidgets.QLineEdit(parent=self.widget1)
        self.txt_shelf_row.setMinimumSize(QtCore.QSize(50, 30))
        self.txt_shelf_row.setObjectName("txt_shelf_row")
        self.grid_row_col.addWidget(self.txt_shelf_row, 5, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.grid_row_col)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_capacity = QtWidgets.QLabel(parent=self.widget1)
        self.lbl_capacity.setObjectName("lbl_capacity")
        self.verticalLayout_2.addWidget(self.lbl_capacity)
        self.txt_shelf_capacity = QtWidgets.QLineEdit(parent=self.widget1)
        self.txt_shelf_capacity.setMinimumSize(QtCore.QSize(100, 30))
        self.txt_shelf_capacity.setObjectName("txt_shelf_capacity")
        self.verticalLayout_2.addWidget(self.txt_shelf_capacity)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(dlg_add_shelf)
        QtCore.QMetaObject.connectSlotsByName(dlg_add_shelf)

    def retranslateUi(self, dlg_add_shelf):
        _translate = QtCore.QCoreApplication.translate
        dlg_add_shelf.setWindowTitle(_translate("dlg_add_shelf", "Thêm kệ mới"))
        self.lbl_title.setText(_translate("dlg_add_shelf", "Thêm kệ"))
        self.btn_secondary.setText(_translate("dlg_add_shelf", "Cancel"))
        self.btn_primary.setText(_translate("dlg_add_shelf", "Save"))
        self.lbl_id.setText(_translate("dlg_add_shelf", "Khu"))
        self.txt_shelf_id.setPlaceholderText(_translate("dlg_add_shelf", "VD: K-A1"))
        self.lbl_row.setText(_translate("dlg_add_shelf", "Dãy"))
        self.lbl_col.setText(_translate("dlg_add_shelf", "Cột"))
        self.txt_shelf_col.setPlaceholderText(_translate("dlg_add_shelf", "VD: 1, 2, 3..."))
        self.txt_shelf_row.setPlaceholderText(_translate("dlg_add_shelf", "VD: A, B, C"))
        self.lbl_capacity.setText(_translate("dlg_add_shelf", "Sức chứa"))
